#!/usr/bin/env bash
set -euo pipefail
# XiaomiWatchLinuxConnect terminal launcher — generated by make-project-runs.sh.
#   launch          → open the project terminal in a new window (default)
#   run [continue]  → internal: prepare env and start opencode2 in this terminal
#   doctor          → health check

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJ_NAME="XiaomiWatchLinuxConnect"
BOX_DIR="$PROJ_DIR"
source "$PROJ_DIR/box/scripts/box-env.sh"

LOCKFILE="/tmp/opencode-$PROJ_NAME.lock"
MODE="${1:-launch}"
ARG2="${2:-}"

if [ "$MODE" = "doctor" ]; then
  bash "$PROJ_DIR/box/scripts/tools/compose-agents.sh" >/dev/null
  bash "$PROJ_DIR/box/scripts/tools/gen-box-config.sh" "$PROJ_DIR" >/dev/null
  echo "$PROJ_NAME setup OK — opencode.json + AGENTS.md regenerated"
  exit 0
fi

if [ "$MODE" = "launch" ]; then
  if [ -f "$LOCKFILE" ]; then
    LOCK_PID=$(cat "$LOCKFILE" 2>/dev/null || true)
    if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null && [ "$ARG2" != "continue" ]; then
      echo "$PROJ_NAME is already running (PID $LOCK_PID)."
      echo "Only one agent per project — use the existing terminal, or close it first."
      exit 0
    fi
  fi
  detect_terminal || true
  if [ -n "${SPAWNED_TERMINAL:-}" ]; then
    spawn_terminal "$PROJ_DIR/box/scripts/$PROJ_NAME.sh" run "$ARG2"
  else
    "$PROJ_DIR/box/scripts/$PROJ_NAME.sh" run "$ARG2" &
  fi
  exit 0
fi

# ── "run" mode ──
SESSIONS_DIR="$PROJ_DIR/box/sessions"
CFG_DIR="$PROJ_DIR/box/cfg"
DATA_DIR="$PROJ_DIR/box/data"
mkdir -p "$SESSIONS_DIR" "$CFG_DIR/opencode" "$DATA_DIR/handoffs" "$DATA_DIR/notes" "$DATA_DIR/limitlogs" "$PROJ_DIR/box/backup" "$PROJ_DIR/box/waste"

bash "$PROJ_DIR/box/scripts/tools/tmpbox.sh" ensure

if [ ! -e "$SESSIONS_DIR/opencode/auth.json" ]; then
  mkdir -p "$SESSIONS_DIR/opencode"
  ln -sf "$HOME/.local/share/opencode/auth.json" "$SESSIONS_DIR/opencode/auth.json"
fi

if [ -f "$LOCKFILE" ]; then
  LOCK_PID=$(cat "$LOCKFILE" 2>/dev/null || true)
  if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null && [ "$LOCK_PID" != "$$" ]; then
    echo "Another $PROJ_NAME instance (PID $LOCK_PID) is running. Stopping it first..."
    kill "$LOCK_PID" 2>/dev/null || true
    sleep 1
  fi
  rm -f "$LOCKFILE"
fi
echo $$ > "$LOCKFILE"
release_lock() { [ "$(cat "$LOCKFILE" 2>/dev/null || true)" = "$$" ] && rm -f "$LOCKFILE"; }
cleanup() {
  release_lock
  bash "$PROJ_DIR/box/scripts/tools/session-backup.sh" >/dev/null 2>&1 || true
}
trap cleanup EXIT

bash "$PROJ_DIR/box/scripts/tools/compose-agents.sh" || true
bash "$PROJ_DIR/box/scripts/tools/gen-box-config.sh" "$PROJ_DIR" || true
cp -f "$PROJ_DIR/box/cli.json" "$CFG_DIR/opencode/cli.json"

source <(bash "$PROJ_DIR/box/scripts/tools/keys.sh" "$PROJ_DIR")

export XDG_DATA_HOME="$SESSIONS_DIR"
export XDG_CONFIG_HOME="$CFG_DIR"
export OPENCODE_CONFIG="$PROJ_DIR/opencode.json"
export OPENCODE_DISABLE_AUTOCOMPACT=1

cd "$PROJ_DIR"

# Buttons cheat-sheet: the box buttons are slash commands + keybinds.
echo "╭─ OpenCodeBox buttons ───────────────────────────────────────╮"
echo "│  type / in the chat (or press Ctrl+P) to see the commands   │"
echo "│  /deepthinking /reasoning /contextlimit /thinklimit         │"
echo "│  /memorycollect /memoryuse /agentsmodes /characters …       │"
echo "│  keybinds: Ctrl+X f favourites · Ctrl+X t thinking ·        │"
echo "│            Shift+Tab switch agent · /boxhelp = full list    │"
echo "╰─────────────────────────────────────────────────────────────╯"

PROMPT_ARGS=()
case "$ARG2" in
  continue) PROMPT_ARGS=(--prompt "Continue the work. Read $DATA_DIR/handoffs/LATEST.md and follow its 'Next steps' in order. Do not re-ask settled questions.") ;;
  new) ;;
  *) PROMPT_ARGS=(--continue) ;;
esac

if [ -r /dev/tty ]; then
  opencode2 --standalone --auto "${PROMPT_ARGS[@]}" </dev/tty &
else
  opencode2 --standalone --auto "${PROMPT_ARGS[@]}" &
fi
echo $! > "$SESSIONS_DIR/opencode/opencode.pid"

nohup bash "$PROJ_DIR/box/scripts/tools/auto-handoff.sh" --watch \
  --name "$PROJ_NAME" \
  --data-dir "$SESSIONS_DIR" \
  --handoffs "$DATA_DIR/handoffs" \
  --pidfile "$SESSIONS_DIR/opencode/opencode.pid" \
  --workdir "$PROJ_DIR" \
  --restart-cmd "$PROJ_DIR/box/scripts/$PROJ_NAME.sh launch continue" \
  >/dev/null 2>&1 &

wait
