#!/usr/bin/env bash
set -euo pipefail
# XiaomiWatchLinuxConnect terminal launcher — generated by make-project-runs.sh.
#   launch          → open the project terminal in a new window (default)
#   run [continue]  → internal: prepare env and start opencode2 in this terminal
#   doctor          → health check

PROJ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJ_NAME="XiaomiWatchLinuxConnect"
BOX_DIR="$PROJ_DIR"
source "$PROJ_DIR/box/scripts/box-env.sh"

LOCKFILE="/tmp/opencode-$PROJ_NAME.lock"
MODE="${1:-launch}"
ARG2="${2:-}"

if [ "$MODE" = "doctor" ]; then
  bash "$PROJ_DIR/box/scripts/tools/compose-agents.sh" >/dev/null
  bash "$PROJ_DIR/box/scripts/tools/gen-box-config.sh" "$PROJ_DIR" >/dev/null
  echo "$PROJ_NAME setup OK — opencode.json + AGENTS.md regenerated"
  exit 0
fi

if [ "$MODE" = "launch" ]; then
  if [ -f "$LOCKFILE" ]; then
    LOCK_PID=$(cat "$LOCKFILE" 2>/dev/null || true)
    if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null && [ "$ARG2" != "continue" ]; then
      echo "$PROJ_NAME is already running (PID $LOCK_PID)."
      echo "Only one agent per project — use the existing terminal, or close it first."
      exit 0
    fi
  fi
  detect_terminal || true
  if [ -n "${SPAWNED_TERMINAL:-}" ]; then
    spawn_terminal "$PROJ_DIR/box/scripts/$PROJ_NAME.sh" run "$ARG2"
  else
    "$PROJ_DIR/box/scripts/$PROJ_NAME.sh" run "$ARG2" &
  fi
  exit 0
fi

# ── "run" mode ──
SESSIONS_DIR="$PROJ_DIR/box/sessions"
CFG_DIR="$PROJ_DIR/box/cfg"
DATA_DIR="$PROJ_DIR/box/sessions"
mkdir -p "$SESSIONS_DIR" "$CFG_DIR/opencode" "$DATA_DIR/notes" "$DATA_DIR/limitlogs" "$DATA_DIR/memory" "$DATA_DIR/exports" "$PROJ_DIR/box/backup" "$PROJ_DIR/box/waste"

bash "$PROJ_DIR/box/scripts/tools/tmpbox.sh" ensure

if [ ! -e "$SESSIONS_DIR/opencode/auth.json" ]; then
  mkdir -p "$SESSIONS_DIR/opencode"
  ln -sf "$HOME/.local/share/opencode/auth.json" "$SESSIONS_DIR/opencode/auth.json"
fi

if [ -f "$LOCKFILE" ]; then
  LOCK_PID=$(cat "$LOCKFILE" 2>/dev/null || true)
  if [ -n "$LOCK_PID" ] && kill -0 "$LOCK_PID" 2>/dev/null && [ "$LOCK_PID" != "$$" ]; then
    echo "Another $PROJ_NAME instance (PID $LOCK_PID) is running. Stopping it first..."
    kill "$LOCK_PID" 2>/dev/null || true
    sleep 1
  fi
  rm -f "$LOCKFILE"
fi
echo $$ > "$LOCKFILE"
release_lock() { [ "$(cat "$LOCKFILE" 2>/dev/null || true)" = "$$" ] && rm -f "$LOCKFILE"; }
cleanup() {
  release_lock
  bash "$PROJ_DIR/box/scripts/tools/session-backup.sh" >/dev/null 2>&1 || true
}
trap cleanup EXIT

bash "$PROJ_DIR/box/scripts/tools/compose-agents.sh" || true
bash "$PROJ_DIR/box/scripts/tools/gen-box-config.sh" "$PROJ_DIR" || true
cp -f "$PROJ_DIR/box/cli.json" "$CFG_DIR/opencode/cli.json"
mkdir -p "$CFG_DIR/opencode/plugins/tui"
cp -f "$PROJ_DIR/box/scripts/tools/tui-plugin/buttonbar.ts" "$CFG_DIR/opencode/plugins/tui/buttonbar.ts" 2>/dev/null || true

source <(bash "$PROJ_DIR/box/scripts/tools/keys.sh" "$PROJ_DIR")

export XDG_DATA_HOME="$SESSIONS_DIR"
export XDG_CONFIG_HOME="$CFG_DIR"
export OPENCODE_CONFIG="$PROJ_DIR/opencode.json"
export OPENCODE_DISABLE_AUTOCOMPACT=1

cd "$PROJ_DIR"

# Give the terminal window a stable title so the button app can find it and
# send it keys (the TUI lives inside the terminal emulator's window).
printf '\033]0;OpenCodeBox: $PROJ_NAME\007\033]2;OpenCodeBox: $PROJ_NAME\007'

# Capture the terminal emulator's PID (its process owns the X window) by
# walking up the process tree from this shell. Deterministic — no focus or
# timing dependence. Fallback: poll the active window for a terminal class.
rm -f "$SESSIONS_DIR/opencode/terminal.wid"
( ppid="$$"
  for i in $(seq 1 12); do
    cmd="$(ps -o comm= -p "$ppid" 2>/dev/null | head -1)"
    case "$cmd" in
      konsole|alacritty|kitty|xterm|foot|wezterm|terminator|lxterminal|sakura|tilix|gnome-terminal*)
        echo "pid $ppid" > "$SESSIONS_DIR/opencode/terminal.wid"
        exit 0 ;;
    esac
    ppid="$(ps -o ppid= -p "$ppid" 2>/dev/null | tr -d ' ')"
    case "$ppid" in ""|0|1) break ;; esac
  done
  for i in $(seq 1 40); do
    WID="$(xprop -root _NET_ACTIVE_WINDOW 2>/dev/null | grep -oE '0x[0-9a-fA-F]+' | head -1)"
    if [ -n "$WID" ]; then
      cls="$(xprop -id "$WID" WM_CLASS 2>/dev/null | tr 'A-Z' 'a-z')"
      case "$cls" in *konsole*|*alacritty*|*kitty*|*xterm*|*foot*|*wezterm*|*terminator*|*gnome-terminal*|*lxterminal*|*sakura*|*tilix*)
        echo "$WID" > "$SESSIONS_DIR/opencode/terminal.wid"
        exit 0 ;;
      esac
    fi
    sleep 0.25
  done ) &

# Buttons cheat-sheet: the box buttons are slash commands + keybinds + the
# button app that opens in your browser.
echo "╭─ OpenCodeBox buttons ───────────────────────────────────────╮"
echo "│  a button APP opened in your browser (buttons + sliders)    │"
echo "│  also: type / in the chat (or Ctrl+P) for slash commands    │"
echo "│  /deepthinking /reasoning /contextlimit /thinklimit …       │"
echo "│  keybinds: Ctrl+X f favourites · Ctrl+X t thinking ·        │"
echo "│            Shift+Tab switch agent · /boxhelp = full list    │"
echo "╰─────────────────────────────────────────────────────────────╯"

PROMPT_ARGS=(--continue)

if [ -r /dev/tty ]; then
  opencode2 --standalone --auto "${PROMPT_ARGS[@]}" </dev/tty &
else
  opencode2 --standalone --auto "${PROMPT_ARGS[@]}" &
fi
echo $! > "$SESSIONS_DIR/opencode/opencode.pid"

# Button bar: native Qt app (PyQt5) — snappy buttons, option lists, sliders,
# setups, live status. Fallbacks: browser app (boxapp.py), then terminal bar.
( sleep 2
  if python3 -c "import PyQt5" >/dev/null 2>&1 && [ -n "${DISPLAY:-}" ]; then
    env -u XDG_CONFIG_HOME -u XDG_DATA_HOME nohup python3 "$PROJ_DIR/box/scripts/tools/boxgui.py" >/dev/null 2>&1 &
  elif command -v xdg-open >/dev/null 2>&1; then
    env -u XDG_CONFIG_HOME -u XDG_DATA_HOME nohup python3 "$PROJ_DIR/box/scripts/tools/boxapp.py" >/dev/null 2>&1 &
  else
    detect_terminal >/dev/null 2>&1 && spawn_terminal "$PROJ_DIR/box/scripts/tools/buttonbar.sh"
  fi ) &

wait
